# Generated by Django 4.2.4 on 2023-10-13 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appfinal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredientes',
            old_name='agua',
            new_name='estilo',
        ),
    ]
