# Generated by Django 4.2.4 on 2023-10-13 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appfinal', '0002_rename_agua_ingredientes_estilo'),
    ]

    operations = [
        migrations.AddField(
            model_name='estilos',
            name='descripcion',
            field=models.TextField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='ingredientes',
            name='estilo',
            field=models.CharField(max_length=40),
        ),
    ]
